// Turkish translations of yengec-api OpenAPI field / parameter / response
// descriptions, keyed by the exact English source string. Used by build-spec.mjs
// to localize the TR reference. Anything not listed falls back to English.
// When yengec-api adds/changes a description, add its Turkish here and re-run
// `npm run build-spec`.
export const FIELD_TR = {
  'A paginated list of orders.': 'Sayfalanmış sipariş listesi.',
  'A paginated list of shippable orders.': 'Kargolanabilir siparişlerin sayfalanmış listesi.',
  'Array of product UUIDs to delete': 'Silinecek ürün UUID dizisi',
  'Array of product UUIDs to restore': 'Geri yüklenecek ürün UUID dizisi',
  'Array of product UUIDs to update': 'Güncellenecek ürün UUID dizisi',
  'Array of tags': 'Etiket dizisi',
  'Array of warehouses': 'Depo dizisi',
  'Cargo integration configuration.': 'Kargo entegrasyon yapılandırması.',
  'Categories deleted': 'Kategoriler silindi',
  'Category deleted': 'Kategori silindi',
  'Category details': 'Kategori detayları',
  'Category updated': 'Kategori güncellendi',
  'Comma-separated IDs.': "Virgülle ayrılmış ID'ler.",
  'Comma-separated integration product IDs.': "Virgülle ayrılmış entegrasyon ürünü ID'leri.",
  'Comma-separated order statuses to filter by.': 'Filtrelenecek, virgülle ayrılmış sipariş durumları.',
  'Comma-separated product UUIDs.': "Virgülle ayrılmış ürün UUID'leri.",
  'Comma-separated relations to include': 'Dahil edilecek, virgülle ayrılmış ilişkiler',
  'Comma-separated relations to include (e.g., orderPackages,customer,shipping,orderItems).':
    'Dahil edilecek, virgülle ayrılmış ilişkiler (örn. orderPackages,customer,shipping,orderItems).',
  'Comma-separated tag IDs': "Virgülle ayrılmış etiket ID'leri",
  'Comma-separated tag IDs.': "Virgülle ayrılmış etiket ID'leri.",
  'Computed capability flags for the company. Applies to both the company-level e_invoice_serial/e_archive_serial fields above and the same fields on each of the company\'s integrations, since configurability depends solely on the company\'s accounting provider.':
    "Firma için hesaplanmış yetenek bayrakları. Yapılandırılabilirlik yalnızca firmanın muhasebe sağlayıcısına bağlı olduğundan, hem yukarıdaki firma seviyesindeki e_invoice_serial/e_archive_serial alanları için hem de firmanın her entegrasyonundaki aynı alanlar için geçerlidir.",
  'Cursor-based pagination metadata (used by notifications and some endpoints)':
    'Cursor tabanlı sayfalama meta verisi (bildirimler ve bazı uç noktalarda kullanılır)',
  "Custom e-archive serial prefix. Only accepted when the company's accounting provider supports it (currently QNB, Isnet, TrendyolEFaturam, Mikro, ELogo, UyumsoftEInvoice, HepsiburadaEFaturam). Whether these fields are configurable is exposed on the owning company's `abilities` (see `CompanyResponse`), not per integration, since it depends solely on the company's accounting provider.":
    "Özel e-arşiv seri ön eki. Yalnızca firmanın muhasebe sağlayıcısı desteklediğinde kabul edilir (şu an QNB, Isnet, TrendyolEFaturam, Mikro, ELogo, UyumsoftEInvoice, HepsiburadaEFaturam). Bu alanların yapılandırılabilir olup olmadığı, yalnızca firmanın muhasebe sağlayıcısına bağlı olduğundan entegrasyon bazında değil, sahibi firmanın `abilities` alanında sunulur (bkz. `CompanyResponse`).",
  "Custom e-invoice serial prefix. Only accepted when the company's accounting provider supports it (currently QNB, Isnet, TrendyolEFaturam, ELogo, UyumsoftEInvoice, HepsiburadaEFaturam).":
    'Özel e-fatura seri ön eki. Yalnızca firmanın muhasebe sağlayıcısı desteklediğinde kabul edilir (şu an QNB, Isnet, TrendyolEFaturam, ELogo, UyumsoftEInvoice, HepsiburadaEFaturam).',
  'Customer created': 'Müşteri oluşturuldu',
  'Customers updated': 'Müşteriler güncellendi',
  "Documents to include. Use 'slip' for shipping slip, 'invoice' for e-invoice, or both":
    "Dahil edilecek belgeler. Kargo fişi için 'slip', e-fatura için 'invoice' veya her ikisini kullanın",
  'E-invoice scenario (basic or commercial).': 'E-fatura senaryosu (basic veya commercial).',
  'E-invoices generated successfully.': 'E-faturalar başarıyla oluşturuldu.',
  'Expenses by period': 'Döneme göre giderler',
  'Field to sort results by.': 'Sonuçların sıralanacağı alan.',
  'Fields to update on each order.': 'Her siparişte güncellenecek alanlar.',
  'Filter by accounting ID (handles null).': 'Muhasebe ID\'sine göre filtrele (null desteklenir).',
  'Filter by cargo code.': 'Kargo koduna göre filtrele.',
  'Filter by cargo company ID.': "Kargo firması ID'sine göre filtrele.",
  'Filter by cargo tracking code.': 'Kargo takip koduna göre filtrele.',
  'Filter by category ID.': "Kategori ID'sine göre filtrele.",
  'Filter by category name.': 'Kategori adına göre filtrele.',
  'Filter by currency code.': 'Para birimi koduna göre filtrele.',
  'Filter by customer name.': 'Müşteri adına göre filtrele.',
  'Filter by deep category status.': 'Derin kategori durumuna göre filtrele.',
  'Filter by e-invoice status.': 'E-fatura durumuna göre filtrele.',
  'Filter by full path.': 'Tam yola göre filtrele.',
  'Filter by integration ID.': "Entegrasyon ID'sine göre filtrele.",
  'Filter by integration product ID.': "Entegrasyon ürünü ID'sine göre filtrele.",
  'Filter by integration.': 'Entegrasyona göre filtrele.',
  'Filter by order identifiers.': 'Sipariş tanımlayıcılarına göre filtrele.',
  'Filter by order package code.': 'Sipariş paketi koduna göre filtrele.',
  'Filter by order type.': 'Sipariş türüne göre filtrele.',
  'Filter by parent category ID.': "Üst kategori ID'sine göre filtrele.",
  'Filter by payment method.': 'Ödeme yöntemine göre filtrele.',
  'Filter by print date range end.': 'Yazdırma tarih aralığı bitişine göre filtrele.',
  'Filter by print date range start.': 'Yazdırma tarih aralığı başlangıcına göre filtrele.',
  'Filter by print status.': 'Yazdırma durumuna göre filtrele.',
  'Filter by product ID.': "Ürün ID'sine göre filtrele.",
  'Filter by push date range end.': 'Gönderim tarih aralığı bitişine göre filtrele.',
  'Filter by push date range start.': 'Gönderim tarih aralığı başlangıcına göre filtrele.',
  'Filter by push-ready flag.': 'Gönderime hazır bayrağına göre filtrele.',
  'Filter by pushed to accounting status.': 'Muhasebeye gönderilme durumuna göre filtrele.',
  'Filter by shipment country code.': 'Gönderi ülke koduna göre filtrele.',
  'Filter by shipment status.': 'Gönderi durumuna göre filtrele.',
  'Filter by shipping availability.': 'Kargo uygunluğuna göre filtrele.',
  'Filter by specific order ID.': "Belirli bir sipariş ID'sine göre filtrele.",
  'Filter by tax rate.': 'Vergi oranına göre filtrele.',
  'Filter expense orders.': 'Gider siparişlerini filtrele.',
  'Filter importable products.': 'İçe aktarılabilir ürünleri filtrele.',
  'Filter only zero tax orders.': 'Yalnızca sıfır vergili siparişleri filtrele.',
  'Filter orders created on or after this date.':
    'Bu tarihte veya sonrasında oluşturulan siparişleri filtrele.',
  'Filter orders created on or before this date.':
    'Bu tarihte veya öncesinde oluşturulan siparişleri filtrele.',
  'Filter orders that are ready to push.': 'Gönderime hazır siparişleri filtrele.',
  'Filter orders that have a cargo code.': 'Kargo kodu olan siparişleri filtrele.',
  'Filter orders that have a cargo tracking code.': 'Kargo takip kodu olan siparişleri filtrele.',
  'Filter orders that have an e-invoice.': 'E-faturası olan siparişleri filtrele.',
  'Filter orders that need editing.': 'Düzenlenmesi gereken siparişleri filtrele.',
  'Filter orders whose cargo code was cancelled (shipment_status = cancelled), as opposed to orders that never had one.':
    'Kargo kodu iptal edilmiş (shipment_status = cancelled) siparişleri, hiç kodu olmayanların aksine filtrele.',
  'Filter sale orders.': 'Satış siparişlerini filtrele.',
  'Images updated successfully': 'Görseller başarıyla güncellendi',
  'Include archived items': 'Arşivlenmiş öğeleri dahil et',
  'Include archived orders.': 'Arşivlenmiş siparişleri dahil et.',
  'Include soft-deleted items': 'Silinmiş (soft-delete) öğeleri dahil et',
  'Include soft-deleted orders.': 'Silinmiş (soft-delete) siparişleri dahil et.',
  'Income by period': 'Döneme göre gelirler',
  'Integration ID': 'Entegrasyon ID',
  'Integration ID with properties': 'Özellikleriyle birlikte entegrasyon ID',
  'Integration ID without properties': 'Özellikleri olmadan entegrasyon ID',
  'Integration product details.': 'Entegrasyon ürünü detayları.',
  'Integration product sales': 'Entegrasyon ürünü satışları',
  'Integration product updated.': 'Entegrasyon ürünü güncellendi.',
  'Inventory data.': 'Envanter verisi.',
  'Job ID': 'İş (job) ID',
  'List of integration properties.': 'Entegrasyon özellikleri listesi.',
  'List of integration warehouses.': 'Entegrasyon depoları listesi.',
  'List of payments': 'Ödeme listesi',
  'List of product images': 'Ürün görselleri listesi',
  'List of statuses.': 'Durum listesi.',
  'Must be "task" to create a background task': 'Arka plan görevi oluşturmak için "task" olmalıdır',
  'Number of items per page': 'Sayfa başına öğe sayısı',
  'Number of results per page.': 'Sayfa başına sonuç sayısı.',
  'Numeric ids of the orders to generate e-invoices for.':
    "E-fatura oluşturulacak siparişlerin sayısal ID'leri.",
  'Offset-based pagination metadata (used by most list endpoints)':
    'Offset tabanlı sayfalama meta verisi (çoğu liste uç noktasında kullanılır)',
  'Operator-based filter (e.g., balance>=100, balance>0)':
    'Operatör tabanlı filtre (örn. balance>=100, balance>0)',
  'Order ID range end.': 'Sipariş ID aralığı bitişi.',
  'Order ID range start.': 'Sipariş ID aralığı başlangıcı.',
  'Order cancelled successfully.': 'Sipariş başarıyla iptal edildi.',
  'Order created successfully.': 'Sipariş başarıyla oluşturuldu.',
  'Order deleted successfully.': 'Sipariş başarıyla silindi.',
  'Order details.': 'Sipariş detayları.',
  'Order numeric IDs (the "id" field, NOT "order_id")':
    'Siparişlerin sayısal ID\'leri ("id" alanı, "order_id" DEĞİL)',
  'Order pulled successfully.': 'Sipariş başarıyla çekildi.',
  'Order shipping information for shippable orders.':
    'Kargolanabilir siparişler için sipariş kargo bilgisi.',
  'Order updated successfully.': 'Sipariş başarıyla güncellendi.',
  'Orders pushed successfully.': 'Siparişler başarıyla gönderildi.',
  'Orders updated successfully.': 'Siparişler başarıyla güncellendi.',
  'Page number (offset-based pagination)': 'Sayfa numarası (offset tabanlı sayfalama)',
  'Paginated array of customers': 'Sayfalanmış müşteri dizisi',
  'Paginated array of product categories': 'Sayfalanmış ürün kategorisi dizisi',
  'Paginated list of categories.': 'Sayfalanmış kategori listesi.',
  'Paginated list of integration products.': 'Sayfalanmış entegrasyon ürünü listesi.',
  'Paginated list of stock events': 'Sayfalanmış stok hareketi listesi',
  'Payment created': 'Ödeme oluşturuldu',
  'Payment information.': 'Ödeme bilgisi.',
  'Product UUID': 'Ürün UUID',
  'Product category created': 'Ürün kategorisi oluşturuldu',
  'Product created': 'Ürün oluşturuldu',
  'Product details': 'Ürün detayları',
  'Product import ID': 'Ürün içe aktarma ID',
  'Product sales': 'Ürün satışları',
  'Product updated': 'Ürün güncellendi',
  'Products deleted successfully': 'Ürünler başarıyla silindi',
  'Products restored successfully': 'Ürünler başarıyla geri yüklendi',
  'Products updated successfully': 'Ürünler başarıyla güncellendi',
  'Products updated.': 'Ürünler güncellendi.',
  'Relations to include.': 'Dahil edilecek ilişkiler.',
  'Sale count': 'Satış adedi',
  'Sales by category': 'Kategoriye göre satışlar',
  'Sales by integration': 'Entegrasyona göre satışlar',
  'Sales by integration category': 'Entegrasyon kategorisine göre satışlar',
  'Search across multiple fields.': 'Birden çok alanda ara.',
  'Search in name': 'İsimde ara',
  'Search in name, phone, email, tc, tax_number': 'İsim, telefon, e-posta, TC, vergi numarasında ara',
  'Search in name, stock_code, barcode, marketplace_product_id.':
    'İsim, stok kodu, barkod, marketplace_product_id alanlarında ara.',
  'Search in name.': 'İsimde ara.',
  'Shipping address details.': 'Kargo adresi detayları.',
  'Shipping updated successfully.': 'Kargo başarıyla güncellendi.',
  'Sort field, prefix with - for desc (e.g. -created_at)':
    'Sıralama alanı; azalan için başına - ekleyin (örn. -created_at)',
  'Sort field.': 'Sıralama alanı.',
  'Sort field. Prefix with - for descending order.':
    'Sıralama alanı. Azalan sıralama için başına - ekleyin.',
  'Sort orders by product': 'Siparişleri ürüne göre sırala',
  'Status counts': 'Durum sayıları',
  'Stock event created': 'Stok hareketi oluşturuldu',
  "Stock quantity change. Prefix with '=' for absolute value (e.g. '=10' sets stock to 10).":
    "Stok miktarı değişimi. Mutlak değer için başına '=' ekleyin (örn. '=10' stoğu 10 yapar).",
  'Tag created': 'Etiket oluşturuldu',
  'Tag deleted': 'Etiket silindi',
  'Tag details': 'Etiket detayları',
  'Tag updated': 'Etiket güncellendi',
  'Task created for generating shipping slips': 'Kargo fişleri oluşturmak için görev oluşturuldu',
  'Task details': 'Görev detayları',
  'The ID of the company.': "Firmanın ID'si.",
  'The ID of the integration.': "Entegrasyonun ID'si.",
  'The order identifier.': 'Sipariş tanımlayıcısı.',
  'The order package identifier.': 'Sipariş paketi tanımlayıcısı.',
  'Total expense amount': 'Toplam gider tutarı',
  'Total income amount': 'Toplam gelir tutarı',
  'Use portrait orientation': 'Dikey yönlendirme kullan',
  'Warehouse created': 'Depo oluşturuldu',
  'Warehouse details': 'Depo detayları',
  'Warehouse updated': 'Depo güncellendi',
  'Whether the accounting provider allows configuring a custom e_archive_serial (currently QNB, Isnet, TrendyolEFaturam, Mikro, ELogo, UyumsoftEInvoice, HepsiburadaEFaturam).':
    'Muhasebe sağlayıcısının özel bir e_archive_serial yapılandırmasına izin verip vermediği (şu an QNB, Isnet, TrendyolEFaturam, Mikro, ELogo, UyumsoftEInvoice, HepsiburadaEFaturam).',
  'Whether the accounting provider allows configuring a custom e_invoice_serial (currently QNB, Isnet, TrendyolEFaturam, ELogo, UyumsoftEInvoice, HepsiburadaEFaturam).':
    'Muhasebe sağlayıcısının özel bir e_invoice_serial yapılandırmasına izin verip vermediği (şu an QNB, Isnet, TrendyolEFaturam, ELogo, UyumsoftEInvoice, HepsiburadaEFaturam).',
  'null=unchecked, {count:0}=no match, {count:N,matches:[...]}=matched':
    'null=kontrol edilmedi, {count:0}=eşleşme yok, {count:N,matches:[...]}=eşleşti',
}
